# -*- coding: utf-8 -*-
"""recycle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umqMGjimQCrRl-d5FprLcVZbsdQHcffZ
"""

import json
import pandas as pd
import plotly.express as px

uk_con = json.load(open("west.geojson", 'r'))

print(uk_con["features"][0]["properties"])

con_id_map = {}
for feature in uk_con['features']:
  feature['id'] = feature['properties']['PCON20CD']
  con_id_map[feature['properties']['PCON20NM']] = feature['id']

df=pd.read_csv("recycle.csv")
df['id'] = df['code']
df.head()
df.tail()

fig = px.choropleth_mapbox(df, locations='id', geojson=uk_con, color='recycle', hover_name="name", mapbox_style="carto-positron", zoom=4, center = {"lat": 55, "lon": 0})
fig.update_layout(width=800,
    height=900,
    autosize=False,
    margin=dict(t=0, b=0, l=0, r=0))
fig.show()

!pip install chart_studio
import chart_studio
import chart_studio.plotly as py

username = 'RusheenB' # your username
api_key = 'hU9oVRitFecZXomYZJXC' # your api key - go to profile > settings > regenerate key
chart_studio.tools.set_credentials_file(username=username, api_key=api_key)
py.plot(fig, filename = 'recycle', auto_open=True)

import plotly.io as pio
pio.write_html(fig, file='recycle.html', auto_open=True)